add debug mode

diff --git a/.local/bin/player b/.local/bin/player
--- a/.local/bin/player
+++ b/.local/bin/player
@@ -1,24 +1,33 @@
-#!/bin/sh -x
+#!/bin/sh
 
 # $0 - mpv wrapper
-# increases range of mpv standard EXIT CODES (currentl inly 4) to use in scripts
-# parce stdout line, return the code based on the text
+# increases range of mpv standard EXIT CODES with CUSTOM EXIT CODES
+# Workflow: parce stdout line, return the code based on the text
+#
 
-DEBUG_ENABE=${DEBUG_ENABLE:-false}
+DEBUG_ENABE=${DEBUG_ENABE:-false}
 
 function trapExit {
 
  mpvExitCode="$(sed -ne '$s/^EXIT CODE: //p' ${@})"
+ customExitCode="${mpvExitCode:-0}"
 
- grep -qaF 'Exiting... (End of file)' ${@} && rm -f ${@} && return 101
- grep -qaF 'Saving state.' ${@}            && rm -f ${@} && return 102
+ grep -qaF 'Exiting... (End of file)' ${@} && customExitCode='101'
+ grep -qaF 'Saving state.' ${@}            && customExitCode='102'
+
+ [ "${DEBUG_ENABE}" '!=' 'false' ] && (
+  case "${customExitCode}" in
+   101 ) echo 'EXIT CODE 101: Normal exit due to end of file'       ;;
+   102 ) echo 'EXIT CODE 101: Normal exit with saving state'        ;;
+   0   ) echo "EXIT CODE ${customExitCode}: Standard good mpv exit code (${mpvExitCode})" ;;
+   *   ) echo "EXIT CODE ${customExitCode}: Standard bad mpv exit code (${mpvExitCode})"  ;;
+  esac ) >&2
 
  rm -f $@
- return ${mpvExitCode}
-#[ "${DEBUG_ENABE}" '!=' 'false' ] && echo debug
+ return ${customExitCode}
 }
 
 TMP_LOG="$(mktemp --suffix=-player)"
 trap 'trapExit "${TMP_LOG}"; exit ${?}' EXIT
 
-(mpv ${@}; echo "EXIT CODE: ${?}") | tee "${TMP_LOG}"
+(mpv "${@}"; echo "EXIT CODE: ${?}") | tee "${TMP_LOG}"
